[package]
name = "triangle"
version = "0.1.0"
edition = "2021"

[lib]
name = "triangle"
path = "src/triangle.rs"

[dependencies]
gl = "0.10.0"
sdl2 = { version = "0.34.0", features = ["bundled", "static-link"] }
renderer = { path = "../renderer" }
utils = { path = "../utils" }
