[package]
name = "triangle"
version = "0.1.0"
edition = "2021"

[dependencies.sdl2]
version = "0.37.0"
features = ["bundled", "static-link"]

[dependencies]
gl = "0.10.0"


[lib]
name = "triangle"
path = "src/main.rs"
