[package]
name = "rust-gl"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/triangle", "crates/gui"]

[dependencies]
triangle = { path = "crates/triangle" }
gui = { path = "crates/gui" }
