[package]
name = "window"
version = "0.1.0"
edition = "2021"

[lib]
name = "window"
path = "src/init.rs"

[dependencies]
gl = "0.10.0"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"] }
